#!/usr/bin/env python3
# -*- coding:utf-8 -*-

"""
Update comic files using new files and old files generated by generate_comic_files.py
This script writes to local_files/new_comic_files.json
"""

import json
import os

file_name = "characters_wikidata.json"

with open(
    os.path.join("local_files", "new_unit_data_files.json"), "w", encoding="utf-8"
) as fo:
    new_json_data = {}
    assert os.path.exists(os.path.join("tracking_files", file_name))
    new_data = json.load(open(os.path.join("tracking_files", file_name)))
    if os.path.exists(os.path.join("local_files", "old_" + file_name)):
        old_data = json.load(open(os.path.join("local_files", "old_" + file_name)))
        for k, v in new_data.items():
            if k not in old_data:
                new_json_data[k] = v
            else:
                different = False
                assert type(v) is dict and type(old_data[k]) is dict
                if v != old_data[k]:
                    new_json_data[k] = v
    else:
        new_json_data.update(new_data)
    json.dump(new_json_data, fo, ensure_ascii=False, indent=4)
